### ISSUE TITLE
Choose a ticket price

### ISSUE THREAD

**Issue by richierocks** [useR2020NYC/proposal#19]
The total costs (excluding Thursday night entertainment) are currently hovering at around $870k. This is based on a capacity for 1500, but it's dangerous to require a sold out conference to break even.

If we make 1000 attendees the break even point, and assume that we can find $200k in sponsorship, we need an average ticket price of $670.

The 2018 conference had a top ticket price of [800 AUD](https://user2018.r-project.org/registration) which is about 580 USD. I think we just have to accept that New York is an expensive city and hope people will pay more. I suggest that four days we charge

Full price

- Industry: $1400
- Academic: $1000
- Student: $600

Early bird

- Industry: $1200
- Academic: $800
- Student: $400

For attendees not joining in with the workshops, 3 days would be 3/4 of the price.

**Comment by richierocks** [comment]
Obviously we'll have to give away some tickets (for example, to sponsors & diversity candidates), and possibly provide discount codes, so those numbers are slightly best case.

**Comment by jaredlander** [comment]
For my two-day conference in NYC we charged $725 general admission and $425 for academics. We gave out 20% discount codes like candy and offered an early bird price. We (over) sold out.

Given this conference is twice as long and these prices are twice as much, that seems about right.

How much did Stanford charge? That would be a good sanity check.

Are we underpricing the workshops? When I put on workshops in the city like for Rob Hyndman, Max Kuhn and the Stan team we charge about $800/day before a 20% discount.

This reminds me, we need to find a ticketing solution. I DO NOT like Eventbrite for a few reasons.

**Comment by richierocks** [comment]
Hmm, useR 2016 had a [top price of $600](http://user2016.r-project.org/#registration). To make the prices that low, they must received discount pricing from Stanford; there is no way we can match that.

I'd rather keep the prices high and offer discounts for people who need financial assistance.

**Comment by jaredlander** [comment]
I agree with you.

What do you think about the workshop pricing?

I wonder if we can get someone senior from the Data Science programs either at Columbia or NYU to help with facilities?

**Comment by richierocks** [comment]
> What do you think about the workshop pricing?

Traditionally, the workshop day at useR is a token amount (<$100). I think this significantly undervalues the day. I think that having it the same price as the other days is as high as we can go in the proposal, but if R Foundation are comfortable with the idea, we can go higher later.

> I wonder if we can get someone senior from the Data Science programs either at Columbia or NYU to help with facilities?

Since the proposal states that "we require all proposals to have substantial involvement from academic partners", I rearranged it so that the workshop day will be in the NYU Kimmel Center. If we can use NYU connections to get a discount on it, that would be great, but I'm not holding my breath.

**Comment by richierocks** [comment]
I bumped up the full price numbers a little, just to be sure.
