### ISSUE TITLE
Choose a venue

### ISSUE THREAD

**Issue by richierocks** [useR2020NYC/proposal#2]
The proposal asks to target 1000 attendees, but since it's NYC, I think we can get 2000 easy. A search on [cvent.com](https://www.cvent.com/venues/results/New%20York%2C%20NY%2C%20USA?filter=eJytjk0LgkAQhv_LnDUGlQpvVqMIfsRqHbosS00kqIG7nqT_3hZB1KlDMDDwzsvzzAS0p6KWm6gmKaIiIQgn0EYNZqMMQwgeeuji3PWxxiBEtDNDxAM4wP3po7Rw0f8q3RwodvmKhCxjWWVE27RIpCjLvHqIOlZ6HLjj3uz6xlhSmm9JpFFm8Rel16M2126v2tFazqrV7EDX9HHTGh5ecYD4DCG0W3PLR8On1-2Ns49kkUioqp_2f8m9AP3lL_rbHSBlbn8&geo=eJx9j01rg0AQhv-K7NnK-sW43jRJgwdNwUiTU9jqRpfqbtis1BD879WWtIGUzmXg5Xl4Z67oKFVHtWZVzqgqmy0bNApRxj6MvVTvppHtTaPII2QiLrjmtF0zWSt6anj5zFvN1ETHmyJbJtn6EG92E_gme1FxUcdyuCFXpC8n9i86Q0Iq3azoWb9ILvSctHRaHraIDT6AbaJWChQ-gWsBxg44mHzPaKKz7HXzyv6QPQCXkF_Zsxyf4IAEN3mc9Prnry__4fI02iVpkR6WSb6NssVqur6jA-_6DoX2g35fD7YD4Lt39Rj7BJxgri2lOPKKzYZWPZuDXmh1Wchqbi1yNH4C87iELA&measurementUnit=IMPERIAL&p=1&sort=CVENT_PICKS&view=LIST) finds 4 hotels that can accommodate that many people.

![screenshot 2018-10-28 17 53 23](https://user-images.githubusercontent.com/197589/47622355-8db56080-dada-11e8-9ec3-4175efe38353.png)

Since useR is traditionally hosted at a university, we also need to see if NYU/Columbia/CUNY can host that many people.

**Comment by jaredlander** [comment]
Very much going to push for Columbia or NYU. Hotels can have the wrong vibe.

**Comment by richierocks** [comment]
I've spoken to people from the [Metropolitan Pavillion](https://www.metropolitanevents.com/location/metropolitan-pavilion/) and the [Altman Building](https://www.altmanbldg.com/venue). These are located in Chelsea, and have a door between them so you don't need to go outside to get from 1 to the other.

The Altman Building has 2 floors: 1 with (seated) capacity 550, and another with capacity 175. It costs $29k day including AV and chair rentals with "some flexibility for a multi-day conference".

The Metropolitan Pavilion has 4 floors: 1 with capacity 1500, and the other three floors with capacity  300 each.

Main floor: $23k/day + $1600 clean up
2nd floor: $8.3k/day + $800 clean up
4th floor: $6.8k/day + $800 clean up
5h floor: $6.45k/day + $800 clean up

Catering we can organize ourselves or use one of their preferred companies. Alcohol we have to use them. Each building has a different exclusive internet provider. We have to use their event management staff.

If we want the whole of both buildings for 4 days, that's

`4 * (29 + 23 + 8.3 + 6.8 + 6.45) + 4 = $298.2k`

I don't think we need the main floor of the MP for the workshop day though which saves us 23k, putting the total at `275.2`.

We could also rearrange things so that all the keynotes happen on the final day, so we'd only need the main floor of the MP for 1 day. This would save another 46k, leaving the total at `229.2`, though that would be slightly weird.

**Comment by richierocks** [comment]
venues picked
